### ISSUE TITLE
Aborting an XHR still results in a timeout callback

### ISSUE THREAD

**Issue by imbcmdth** [naugtur/xhr#104]
The issue seems to be around here: https://github.com/Raynos/xhr/blob/master/index.js#L184

When XHRs are aborted, the timeout isn't cleared. When the timer function is invoked, it doesn't first check the status of the XHR before executing the callback.

A possible solution is to listen for the `abort` event and clear the timeout.

**Comment by naugtur** [comment]
Confirmed, nice catch. Thanks.

I can't promise I'll fix it this week, so let me know if you'd like to PR this with a test ;)

**Comment by TehShrike** [comment]
What's the correct behavior?  Should the callback be called with a timeout error right away?

I started to write a test and then realized I didn't know what I should be asserting.

Not calling the callback at all sounds like a way to tempt Zalgo.

**Comment by TehShrike** [comment]
Based on issue #93, I propose that

1. the callback should be called immediately when the abort is fired
2. the error object should be augmented with `err.code = 'ECONNRESET'`

Does that sound reasonable?  I don't like the idea of no longer calling the callback at all, if only for the reason that it would be a breaking API change.

**Comment by naugtur** [comment]
We want to mimic how request/request is reacting to `.abort()`
I checked quickly and it does not call the callback. Nothing else happens after abort.

This issue is about the internal timeout we use instead of the one on `XMLHttpRequest` object, which doesn't work in some browsers. 

Here's a solution https://github.com/Raynos/xhr/tree/abort-timeout, but it'd require extensive cross-browser testing before merging in.

**Comment by naugtur** [comment]
Looking for volunteers to test in IEs, Safari etc.
