### ISSUE TITLE
Is there a reason err isn't triggered for non-200 responses?

### ISSUE THREAD

**Issue by timwis** [naugtur/xhr#133]
I've expected `err` to be `true` if `response.statusCode !== 200`, but that's not the case with this library. So my error check lines tend to look like this:

```javascript
if (err || response.statusCode !== 200) return done(new Error('Error updating case'))
```

Which is actually too long of a line for some readability standards, so it ends up taking up 3 lines:

```javascript
if (err || response.statusCode !== 200) {
  return done(new Error('Error updating case'))
}
```

Is there a reason that `err` doesn't have anything to do with `response.statusCode`?

**Comment by naugtur** [comment]
There sure is.

Simply put - `xhr` is implementing a subset of https://github.com/request/request api and `request` works that way.

There's also reasoning behind it - your http request was successful and all information is transfered without errors. The server responded and then closed connection (or not) as expected. 

I know it's surprising at first because of how influential jquery was all those years, but for actual http request an error is when connection fails or breaks. Everything else is your http request working correctly, but the application may return a status code that describes status of the operation requested, not the http exchange.

**Comment by timwis** [comment]
Thanks for the background, makes sense.
