### ISSUE TITLE
No types for xhr

### ISSUE THREAD

**Issue by ivanzwb** [naugtur/xhr#169]
Could you help provide the types for xhr?

**Comment by jmeas** [comment]
Thanks for the issue, @ivanzwb ! My guess is that none of the current maintainers of this library use TypeScript; otherwise, it’s likely that there would be the types in here. I’d be open to reviewing a PR that adds types.

Alternatively, they could be added to [the DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) project.

If you have time to make a PR, we’d appreciate it! Thanks!

**Comment by ivanzwb** [comment]
[index.d.zip](https://github.com/naugtur/xhr/files/1186838/index.d.zip)
 dts-gen generated types.

**Comment by naugtur** [comment]
fixed by #174

**Comment by r00ger** [comment]
@naugtur, will you please release the next version that incudes typings?

**Comment by naugtur** [comment]
v2.5.0 released.
@r00ger
